-d D:\FPGA_practice\i2c_sensors\i2c_fpga\impl\gwsynthesis\i2c_fpga.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst D:\FPGA_practice\i2c_sensors\i2c_fpga\src\i2c_fpga.cst
-cfg D:\FPGA_practice\i2c_sensors\i2c_fpga\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
